CREATE TABLE `tab_documentos_ficha_clinica` (
  `rowid` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_apellido` varchar(70) DEFAULT NULL,
  `cedula_pasaporte` varchar(75) DEFAULT NULL,
  `fecha_nacimiento` varchar(75) DEFAULT NULL,
  `lugar_nacimiento` varchar(75) DEFAULT NULL,
  `estado_civil` varchar(75) DEFAULT NULL,
  `n_hijos` varchar(75) DEFAULT NULL,
  `sexo` varchar(75) DEFAULT NULL,
  `edad` varchar(75) DEFAULT NULL,
  `ocupacion` varchar(75) DEFAULT NULL,
  `direccion_domicilio` varchar(75) DEFAULT NULL,
  `emergencia_call_a` varchar(75) DEFAULT NULL,
  `emergencia_telefono` varchar(75) DEFAULT NULL,
  `telefono_convencional` varchar(75) DEFAULT NULL,
  `operadora` varchar(75) DEFAULT NULL,
  `celular` varchar(75) DEFAULT NULL,
  `email` varchar(75) DEFAULT NULL,
  `twiter` varchar(75) DEFAULT NULL,
  `lugar_trabajo` varchar(75) DEFAULT NULL,
  `telefono_trabajo` varchar(75) DEFAULT NULL,
  `posee_seguro` varchar(75) DEFAULT NULL,
  `motivo_consulta` varchar(750) DEFAULT NULL,
  `tiene_enfermedades` varchar(1000) DEFAULT NULL,
  `otras_enfermedades` varchar(75) DEFAULT NULL,
  `esta_algun_tratamiento_medico` varchar(1000) DEFAULT NULL,
  `cual_tratamiento_medico` varchar(75) DEFAULT NULL,
  `tiene_problema_hemorragico` varchar(1000) DEFAULT NULL,
  `cual_problema_hemorragico` varchar(75) DEFAULT NULL,
  `alergico_medicamento` varchar(1000) DEFAULT NULL,
  `cual_alergico_medicamento` varchar(75) DEFAULT NULL,
  `toma_medicamento` varchar(1000) DEFAULT NULL,
  `cual_toma_medicamento` varchar(75) DEFAULT NULL,
  `esta_embarazada` varchar(1000) DEFAULT NULL,
  `cual_esta_embarazada` varchar(75) DEFAULT NULL,
  `enfermedades_hereditarias` varchar(1000) DEFAULT NULL,
  `cual_enfermedades_hereditarias` varchar(75) DEFAULT NULL,
  `que_toma_ult_24horass` varchar(70) DEFAULT NULL,
  `resistente_medicamento` varchar(75) DEFAULT NULL,
  `hemorragia_bucales` varchar(1000) DEFAULT NULL,
  `complicacion_masticar` varchar(1000) DEFAULT NULL,
  `habitos_consume` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`rowid`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8
;
